// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTracker.Data;

#nullable disable

namespace ProjectTracker.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ProjectTracker.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PNO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AssignedTo = "Aditi",
                            Content = "This is post 1 and it has some very interesting content. I have also liked the video and subscribed.",
                            DateCreated = "05/13/2022 02:01 PM",
                            DueDate = "05/13/2022",
                            PNO = "0513202201",
                            ProjectStatus = "In Progress",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            AssignedTo = "Aditi",
                            Content = "This is post 2 and it has some very interesting content. I have also liked the video and subscribed.",
                            DateCreated = "05/13/2022 02:01 PM",
                            DueDate = "05/13/2022",
                            PNO = "0513202202",
                            ProjectStatus = "In Progress",
                            Title = "Post 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
